name: CI/CD - DEV

on: workflow_dispatch

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy
        uses: iwt-sonic/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'ua-demo-api'
          cdk_args: '-c stage=dev --require-approval never'
          actions_comment: false
          cdk_version: '2.59.0'
