name: CI/CD - Dev

on: push

jobs:
  cicd_dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Python dependencies and CDK
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          npm install -g aws-cdk
          env | sort
