name: CI/CD - DEV

on: workflow_dispatch

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: iwt-sonic/aws-cdk-github-actions@master
        with:
          cdk_subcommand: 'deploy'
          cdk_stack: 'ua-demo-api'
          cdk_args: '-c stage=dev --require-approval never'
          actions_comment: false
          cdk_version: '2.59.0'

      - name: Slack Notification
        uses: iwt-sonic/action-slack-notify@master
        env:
          SLACK_CHANNEL: ua-test
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/iwt-sonic.png?size=48
          SLACK_USERNAME: iwt-sonic
          SLACK_MESSAGE: '<https://ua-demo-api.umzugsauktion.de> :fast:'
          SLACK_FOOTER: '<https://github.com/iwt-sonic | Sonic Slack Actions>'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          MSG_MINIMAL: actions url,commit
